Feature unit test
wolox-training/jv-java pull request #13
Opened 2021-05-20 04:27 UTC by jodelvecchio

## Summary
- Test unit to layers DAO and MVC
## Trello Card
https://trello.com/c/0TLHwGgf

2021-05-20 12:55 UTC, juandbc commented on src/test/java/wolox/training/controllers/BookControllerTest.java
> +        final String url = "/api/books";
Como sugerencia, esta  URL puede ser una constante y cuando sea necesario, concatenar lo necesario🙂

2021-05-20 13:16 UTC, juandbc requested changes

2021-05-20 13:16 UTC, juandbc commented on src/test/java/wolox/training/repositories/UserRepositoryTest.java
> +        userDB.setBirthdate(LocalDate.now());
Aquí quedó mal la fecha, por eso fallan los test

2021-05-20 13:16 UTC, juandbc commented on src/test/java/wolox/training/repositories/BookRepositoryTest.java
> +        Book bookPersisted = entityManager.persist(book);
Aquí deberíamos usar el repository en lugar del entityManager
```suggestion
        Book bookPersisted = bookRepository.save(book);
```

2021-05-20 13:16 UTC, juandbc commented on src/test/java/wolox/training/repositories/BookRepositoryTest.java
> +            entityManager.flush();
Acá también el repository
```suggestion
            bookRepository.save(book);
```

2021-05-20 13:16 UTC, juandbc commented on src/test/java/wolox/training/repositories/UserRepositoryTest.java
> +            entityManager.flush();
```suggestion
            userRepository.saveuser);
```

2021-05-20 13:16 UTC, juandbc commented on src/test/java/wolox/training/repositories/UserRepositoryTest.java
> +        assertThrows(PersistenceException.class,() -> {
Esta excepción es la que lanza el `EntityManager`, pero internamente Spring la convierte a `DataIntegrityViolationException` cuando se usa `JpaRepository`
```suggestion
        assertThrows(DataIntegrityViolationException.class,() -> {
```

2021-05-20 13:16 UTC, juandbc commented on src/test/java/wolox/training/repositories/BookRepositoryTest.java
> +        assertThrows(PersistenceException.class,() -> {
```suggestion
        assertThrows(DataIntegrityViolationException.class,() -> {
```

2021-05-20 14:23 UTC, juandbc approved these changes

2021-05-21 19:25 UTC, Jimenarosello approved these changes
Nice job! 😊

2021-05-21 19:25 UTC, Jimenarosello commented on src/test/java/wolox/training/controllers/BookControllerTest.java
> +    public void whenFindOneWhichExists_thenBookIsReturned() throws Exception {
In general, we use the guideline `given_when_then` to make test names more descriptive 
For example, in this case the name could be `givenExistingBook_whenFindOne_thenBookIsReturned`  
This is just a suggestion, you don't need to change it 😄

2021-05-25 16:05 UTC, merged